import Pokemon from '@/models/Pokemon';

const pokemon: Pokemon[] = [
  { name: 'Sprigatito' },
  { name: 'Floragato' },
  { name: 'Meowscarada' },
  { name: 'Fuecoco' },
  { name: 'Crocalor' },
  { name: 'Skeledirge' },
  { name: 'Quaxly' },
  { name: 'Quaxwell' },
  { name: 'Quaquaval' },
  { name: 'Lechonk' },
  { name: 'Oinkologne' },
  { name: 'Dundunsparce' },
  { name: 'Tarountula' },
  { name: 'Spidops' },
  { name: 'Nymble' },
  { name: 'Lokix' },
  { name: 'Rellor' },
  { name: 'Rabsca' },
  { name: 'Greavard' },
  { name: 'Houndstone' },
  { name: 'Flittle' },
  { name: 'Espartha' },
  { name: 'Firagiraf' },
  { name: 'Wiglett' },
  { name: 'Wugtrio' },
  { name: 'Dondozo' },
  { name: 'Veluza' },
  { name: 'Finizen' },
  { name: 'Palafin' },
  { name: 'Smoliv' },
  { name: 'Dolliv' },
  { name: 'Arboliva' },
  { name: 'Capsakid' },
  { name: 'Scovillain' },
  { name: 'Tadbulb' },
  { name: 'Bellibolt' },
  { name: 'Varoom' },
  { name: 'Revavroom' },
  { name: 'Orthworm' },
  { name: 'Tandemous' },
  { name: 'Maushold' },
  { name: 'Cetoddle' },
  { name: 'Cetitan' },
  { name: 'Arbolovia' },
  { name: 'Arctibax' },
  { name: 'Baxcalibur' },
  { name: 'Tatsugiri' },
  { name: 'Cyclizar' },
  { name: 'Pawmi' },
  { name: 'Pawmo' },
  { name: 'Pawmot' },
  { name: 'Wattrel' },
  { name: 'Kilowattrel' },
  { name: 'Bombirdier' },
  { name: 'Squawkability' },
  { name: 'Flamigo' },
  { name: 'Klawf' },
  { name: 'Nacli' },
  { name: 'Naclistack' },
  { name: 'Garganacl' },
  { name: 'Glimmet' },
  { name: 'Glimmora' },
  { name: 'Shroodle' },
  { name: 'Grafaiai' },
  { name: 'Fidough' },
  { name: 'Dachsbun' },
  { name: 'Maschiff' },
  { name: 'Mabosstiff' },
  { name: 'Bramblin' },
  { name: 'Brambleghast' },
  { name: 'Gimmighoul' },
  { name: 'Gholdengo' },
  { name: 'Great Tusk' },
  { name: 'Brute Bonnet' },
  { name: 'Sandy Shocks' },
  { name: 'Scream Tail' },
  { name: 'Flutter Mane' },
  { name: 'Slither Wing' },
  { name: 'Roaring Moon' },
  { name: 'Iron Treads' },
  { name: 'Iron Moth' },
  { name: 'Iron Hands' },
  { name: 'Iron Jugulis' },
  { name: 'Iron Thorns' },
  { name: 'Iron Bundle' },
  { name: 'Iron Valiant' },
  { name: 'Ting-Lu' },
  { name: 'Chien-Pao' },
  { name: 'Wo-Chien' },
  { name: 'Chi-Yu' },
  { name: 'Koraidon' },
  { name: 'Miraidon' },
  { name: 'Tinkatink' },
  { name: 'Tinkatuff' },
  { name: 'Tinkaton' },
  { name: 'Charcadet' },
  { name: 'Armarouge' },
  { name: 'Ceruledge' },
  { name: 'Toedscool' },
  { name: 'Toedscruel' },
  { name: 'Kingambit' },
  { name: 'Clodsire' },
  { name: 'Anihilape' }
];

export default pokemon;
